services:
  postgres:
    image: postgres:17
    container_name: eventflow-postgres

    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow

    ports:
      - "5433:5432"

    volumes:
      - eventflow-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventflow -d eventflow"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  eventflow-postgres-data: