services:
  postgres:
    image: postgres:17
    container_name: eventflow-postgres

    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow

    ports:
      - "5433:5432"

    volumes:
      - eventflow-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventflow -d eventflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: eventflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: eventflow
      RABBITMQ_DEFAULT_PASS: eventflow
    volumes:
      - eventflow-rabbitmq-data:/var/lib/rabbitmq

volumes:
  eventflow-postgres-data:
  eventflow-rabbitmq-data: