spring.application.name=eventflow-api

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

app.auth.cookie-name=eventflow_token
app.auth.cookie-secure=${AUTH_COOKIE_SECURE:true}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:3600000}