spring.application.name=eventflow-api

spring.datasource.url=jdbc:postgresql://localhost:5433/eventflow
spring.datasource.username=eventflow
spring.datasource.password=eventflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false