CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_role
        CHECK (role IN ('PARTICIPANT', 'ORGANIZER'))
);

CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description  TEXT NOT NULL,
    location VARCHAR(255) NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    capacity INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_events_organizer
        FOREIGN KEY (organizer_id)
            REFERENCES users (user_id),

    CONSTRAINT chk_events_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_events_price
        CHECK (price >= 0),

    CONSTRAINT chk_events_dates
        CHECK (start_date < end_date),

    CONSTRAINT chk_events_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED', 'FINISHED'))
);

CREATE INDEX idx_events_organizer_id
    ON events (organizer_id);

CREATE TABLE registrations
(
    registration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    reservation_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_registrations_participant
        FOREIGN KEY (participant_id)
            REFERENCES users (user_id),

    CONSTRAINT fk_registrations_event
        FOREIGN KEY (event_id)
            REFERENCES events (event_id),

    CONSTRAINT chk_registrations_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED'))
);

CREATE UNIQUE INDEX uq_registrations_active_participant_event
    ON registrations (participant_id, event_id) WHERE status IN ('PENDING', 'CONFIRMED');

CREATE INDEX idx_registrations_participant_id
    ON registrations (participant_id);

CREATE INDEX idx_registrations_event_id
    ON registrations (event_id);

CREATE TABLE payments
(
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL UNIQUE,
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_registration
        FOREIGN KEY (registration_id)
            REFERENCES registrations (registration_id),

    CONSTRAINT chk_payments_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payments_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'FAILED',
                'EXPIRED',
                'CANCELLED',
                'REFUNDED'
            )
        )
);

CREATE TABLE tickets
(
    ticket_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID NOT NULL UNIQUE,
    registration_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tickets_registration
        FOREIGN KEY (registration_id)
            REFERENCES registrations (registration_id),

    CONSTRAINT chk_tickets_status
        CHECK (status IN ('ACTIVE', 'CANCELLED'))
);